name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you use

      - name: Install dependencies at backend
        run:  |
          cd backend 
          npm install

      - name: Run ESLint at backend
        run:  |
          cd backend
          npx eslint .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you use

      - name: Install dependencies at backend
        run: |
          cd backend
          npm install

      - name: Run Jest tests at backend
        run: |
          cd backend
          npm test
